name: project_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_skill: ^0.2.6
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.4.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.2.0

  google_sign_in: ^6.2.1

  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  http: ^1.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/onboarding_1.png
    - lib/assets/onboarding_2.png
    - lib/assets/apple.png
    - lib/assets/google.png
    - lib/assets/facebook.png
    - lib/assets/image.jpg
    - .env
