// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOMovVoXQbjxBQgODiB6RZNIEsS6JxQB8',
    appId: '1:932295588051:web:a4cddd4f294785e1037c26',
    messagingSenderId: '932295588051',
    projectId: 'fixongo-dad40',
    authDomain: 'fixongo-dad40.firebaseapp.com',
    storageBucket: 'fixongo-dad40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOMovVoXQbjxBQgODiB6RZNIEsS6JxQB8',
    appId: '1:932295588051:android:c8327b7a388b94a8037c26',
    messagingSenderId: '932295588051',
    projectId: 'fixongo-dad40',
    storageBucket: 'fixongo-dad40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOMovVoXQbjxBQgODiB6RZNIEsS6JxQB8',
    appId: '1:932295588051:ios:c8327b7a388b94a8037c26', // Placeholder
    messagingSenderId: '932295588051',
    projectId: 'fixongo-dad40',
    storageBucket: 'fixongo-dad40.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOMovVoXQbjxBQgODiB6RZNIEsS6JxQB8',
    appId: '1:932295588051:ios:c8327b7a388b94a8037c26', // Placeholder
    messagingSenderId: '932295588051',
    projectId: 'fixongo-dad40',
    storageBucket: 'fixongo-dad40.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOMovVoXQbjxBQgODiB6RZNIEsS6JxQB8',
    appId: '1:932295588051:web:c8327b7a388b94a8037c26', // Placeholder
    messagingSenderId: '932295588051',
    projectId: 'fixongo-dad40',
    authDomain: 'fixongo-dad40.firebaseapp.com',
    storageBucket: 'fixongo-dad40.firebasestorage.app',
  );
} // Closed the class
