// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCah5Y3aaW4ROSsGd5aseWOPNOGYO_aiGs',
    appId: '1:1027971540802:web:100ad136fbbbd9946fcadb',
    messagingSenderId: '1027971540802',
    projectId: 'fixongo-b8337',
    authDomain: 'fixongo-b8337.firebaseapp.com',
    storageBucket: 'fixongo-b8337.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCky40HbTpUdHzopKC8cP6ncw7fyZ-uiZo',
    appId: '1:1027971540802:android:9ca87e6a0d568f596fcadb',
    messagingSenderId: '1027971540802',
    projectId: 'fixongo-b8337',
    storageBucket: 'fixongo-b8337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn8cjIwdpQGWIXDSdI9gD39gljTZ9VXmE',
    appId: '1:1027971540802:ios:5589c8697f7c2e626fcadb',
    messagingSenderId: '1027971540802',
    projectId: 'fixongo-b8337',
    storageBucket: 'fixongo-b8337.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn8cjIwdpQGWIXDSdI9gD39gljTZ9VXmE',
    appId: '1:1027971540802:ios:5589c8697f7c2e626fcadb',
    messagingSenderId: '1027971540802',
    projectId: 'fixongo-b8337',
    storageBucket: 'fixongo-b8337.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCah5Y3aaW4ROSsGd5aseWOPNOGYO_aiGs',
    appId: '1:1027971540802:web:bc7711c4658465346fcadb',
    messagingSenderId: '1027971540802',
    projectId: 'fixongo-b8337',
    authDomain: 'fixongo-b8337.firebaseapp.com',
    storageBucket: 'fixongo-b8337.firebasestorage.app',
  );

} // Closed the class